### ISSUE TITLE
gmap Underflow Issue

### ISSUE THREAD

**Issue by joj3810** [bokeh/rbokeh#198]
An issue with Google Maps objects underflowing out from their frames has been affecting rbokeh in recent weeks.

The issue was raised in the Google group and apparently fixed for the newest release of the library, but the issue is still in rbokeh.
https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/4GaPygTvhC8
https://github.com/bokeh/bokeh/issues/5801

![image](https://cloud.githubusercontent.com/assets/25266696/22694618/4a573d10-ed8b-11e6-9c1d-c670ae3de3e3.png)

**Comment by bryevdv** [comment]
This is fixed only in the master branch, it is not yet in a full release. It is in the last dev build, which can be installed with conda:

        conda install -c bokeh/c/dev bokeh 

Or alternatively you can build Bokeh from source using the instructions in the dev guide. 

Thanks,

Bryan

**Comment by bryevdv** [comment]
Sorry on my phone I didn't notice this was an RBokeh question. However the above information about the fix only being in a dev build at this point is correct.

**Comment by joj3810** [comment]
Great, thanks for clarifying.

**Comment by hafen** [comment]
I've updated rbokeh to use the latest production version of BokehJS (0.12.4) and I'm still doing some testing of other things on it, but this issue still exists with this version. @bryevdv, will the fix be in the next release?

**Comment by bryevdv** [comment]
@hafen yes the fix is in recent dev builds and will be in `0.12.5` this week (along with many other gmap fixes and improvements)

**Comment by hafen** [comment]
Thanks @bryevdv. I'm working this into rbokeh now.

**Comment by hafen** [comment]
This has been fixed in `hafen/rbokeh`. You can verify with `devtools::install_github("hafen/rbokeh"). I'll be merging here and pushing to CRAN soon.
